name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 12 * * *' # roda todo dia às 12h UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl https://euwmjhuewnjymhzbedkh.supabase.co/rest/v1/notpause \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
